extern double fitness[1000];
extern double fitness_children[1000];
extern double sumFitness;
extern double maxFitness;
extern double minFitness;
extern double avgFitness;
extern int popSize;
extern int lchrom;
extern double normal_fitness;
extern double comulative ;
extern double comulative_fitness[1000];
extern double comulative_sub[1000];
extern int population[1000][50];
extern int children[1000][50];
extern int ci1[50];
extern int ci2[50];
