extern double fitness[100];
extern double sumFitness;
extern double maxFitness;
extern double minFitness;
extern double avgFitness;
extern int popSize;
extern int lchrom;
extern double normal_fitness;
extern double comulative ;
extern double comulative_fitness[100];
extern double comulative_sub[100];
extern int population[100][50];
